# Generated by Django 3.1.5 on 2021-01-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_image_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='post',
            new_name='Category',
        ),
        migrations.RemoveField(
            model_name='image',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='image',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
